FROM openjdk:21-slim

ARG JAVA_OPTS
ARG SPRING_PROFILES_ACTIVE=development
ARG SERVICE_VERSION=1.0.0

ENV SERVICE_VERSION=$SERVICE_VERSION
ENV JAVA_OPTS=$JAVA_OPTS
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE

ADD target/notification-service-$SERVICE_VERSION.jar notification-service.jar

EXPOSE 8081

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -DSPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE -jar notification-service.jar"]
