spring:
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework: error
    org.springframework.security: debug
    com.yowyob.identity: DEBUG

api:
  version: v1
  context: /api/${api.version}

client:
  super:
    id: cffe3990-6f0e-11e8-b750-4d8614c940ff
    secret: $2a$12$.5qlSA.5Gjp9.TRlEflnXukLlYUz/eNRhLgFKubk6PIoL8GM7GzLu
    scope: trust, system
    grant-types: password, refresh_token
