server:
    port: 4014
    error:
        include-message: always
eureka:
    client:
     serviceUrl:
        default: http://localhost:8761/eureka

spring:
    application:
        name: notification
    cassandra:
        local-datacenter: datacenter1
        keyspace-name: yowyobdbnotification
        port: 9042
        contact-points: localhost



yowyob:
    openapi:
        prod-url: http://localhost:4000
        dev-url: http://localhost:4000


# https://drive.google.com/file/d/11_ZogAQTbK1mUdtoc9Z6xKj0tK-4UwfS/view?usp=sharing